shopware:
  filesystem:
      private:
          type: "azure"
          visibility: "private"
          config:
              storage_account_name: "%env(AZURE_STORAGE_ACCOUNT_NAME)%"
              storage_account_key: "%env(AZURE_STORAGE_ACCOUNT_KEY)%"
              storage_account_container: "%env(AZURE_STORAGE_ACCOUNT_PRIVATE_CONTAINER)%"
      public: &public_azure
          url: "%env(AZURE_CDN_URL)%"
          type: "azure"
          config:
              storage_account_name: "%env(AZURE_STORAGE_ACCOUNT_NAME)%"
              storage_account_key: "%env(AZURE_STORAGE_ACCOUNT_KEY)%"
              storage_account_container: "%env(AZURE_STORAGE_ACCOUNT_PUBLIC_CONTAINER)%"
      asset: *public_azure
      theme: *public_azure
      temp:
          type: "local"
          config:
                root: "%kernel.project_dir%/var"