version: "3.5"

services:
  tests:
    depends_on:
      - test-db
    image: ${TAG}
    environment:
      DATABASE_HOST: test-db
      DATABASE_PORT: 3306
      DATABASE_NAME: test
      DATABASE_USER: test
      DATABASE_PASSWORD: test
      REDIS_HOST: test
      REDIS_DB: 1
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ['/bin/sh', /entrypoint.sh]

  test-db:
    image: mariadb:10.4
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --innodb-file-format=Barracuda,
        --innodb-large-prefix=1,
        --innodb-file-per-table=1,
        --lower-case-table-names=1,
      ]